#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : DML
Version  : 0.1.3.beta
Release  : 1
URL      : https://github.com/intel/DML/archive/refs/tags/v0.1.3-beta.tar.gz
Source0  : https://github.com/intel/DML/archive/refs/tags/v0.1.3-beta.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: DML-bin = %{version}-%{release}
Requires: DML-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
Intel® Data Mover Library (Intel® DML) Beta
=================================================
[Get Started](#get-started) | [Documentation](#documentation) | [License](#license) | [GitHub repository](https://github.com/intel-innersource/libraries.performance.accelerators.dml.dml-library.git)

%package bin
Summary: bin components for the DML package.
Group: Binaries
Requires: DML-license = %{version}-%{release}

%description bin
bin components for the DML package.


%package dev
Summary: dev components for the DML package.
Group: Development
Requires: DML-bin = %{version}-%{release}
Provides: DML-devel = %{version}-%{release}
Requires: DML = %{version}-%{release}

%description dev
dev components for the DML package.


%package license
Summary: license components for the DML package.
Group: Default

%description license
license components for the DML package.


%prep
%setup -q -n DML-0.1.3-beta
cd %{_builddir}/DML-0.1.3-beta

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631892897
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1631892897
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/DML
cp %{_builddir}/DML-0.1.3-beta/LICENSE %{buildroot}/usr/share/package-licenses/DML/aee878e8774dfaebce46c699c0e0537e8646c1b9
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/dml/cmake/DmlConfig-relwithdebinfo.cmake
/usr/dml/cmake/DmlConfig.cmake
/usr/dml/cmake/DmlConfigVersion.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/job_api_samples

%files dev
%defattr(-,root,root,-)
/usr/include/dml/data_view.hpp
/usr/include/dml/detail/buffer.hpp
/usr/include/dml/detail/execute.hpp
/usr/include/dml/detail/handler.hpp
/usr/include/dml/detail/submit.hpp
/usr/include/dml/detail/utils.hpp
/usr/include/dml/dml.hpp
/usr/include/dml/execute.hpp
/usr/include/dml/execution_interface.hpp
/usr/include/dml/execution_path.hpp
/usr/include/dml/handler.hpp
/usr/include/dml/include/dml.h
/usr/include/dml/include/dmldefs.h
/usr/include/dml/operations.hpp
/usr/include/dml/sequence.hpp
/usr/include/dml/submit.hpp
/usr/include/dml_common/range_check.hpp
/usr/include/dml_common/result.hpp
/usr/include/dml_common/status_code.hpp
/usr/include/dml_common/types.hpp
/usr/include/dml_ml/apply_delta.hpp
/usr/include/dml_ml/awaiter.hpp
/usr/include/dml_ml/batch.hpp
/usr/include/dml_ml/cache_flush.hpp
/usr/include/dml_ml/compare.hpp
/usr/include/dml_ml/compare_pattern.hpp
/usr/include/dml_ml/copy_crc.hpp
/usr/include/dml_ml/crc.hpp
/usr/include/dml_ml/create_delta.hpp
/usr/include/dml_ml/dualcast.hpp
/usr/include/dml_ml/fill.hpp
/usr/include/dml_ml/hardware_path.hpp
/usr/include/dml_ml/mem_copy.hpp
/usr/include/dml_ml/mem_move.hpp
/usr/include/dml_ml/operation.hpp
/usr/include/dml_ml/result.hpp
/usr/include/dml_ml/software_path.hpp
/usr/lib64/libdml.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/DML/aee878e8774dfaebce46c699c0e0537e8646c1b9
