#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : DML
Version  : 1.0.0
Release  : 2
URL      : https://github.com/intel/DML/archive/v1.0.0/DML-1.0.0.tar.gz
Source0  : https://github.com/intel/DML/archive/v1.0.0/DML-1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: DML-bin = %{version}-%{release}
Requires: DML-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : util-linux-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-utility-include.patch

%description
Intel® Data Mover Library (Intel® DML)
=================================================
[Get Started](#get-started) | [Documentation](#documentation) | [License](#license) | [GitHub repository](https://github.com/intel/DML)

%package bin
Summary: bin components for the DML package.
Group: Binaries
Requires: DML-license = %{version}-%{release}

%description bin
bin components for the DML package.


%package dev
Summary: dev components for the DML package.
Group: Development
Requires: DML-bin = %{version}-%{release}
Provides: DML-devel = %{version}-%{release}
Requires: DML = %{version}-%{release}

%description dev
dev components for the DML package.


%package license
Summary: license components for the DML package.
Group: Default

%description license
license components for the DML package.


%prep
%setup -q -n DML-1.0.0
cd %{_builddir}/DML-1.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680629700
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake .. -DDML_BUILD_TESTS=OFF \
-DDML_BUILD_EXAMPLES=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1680629700
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/DML
cp %{_builddir}/DML-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/DML/d6b97f1ba83cfecb7d9dcb7165e8d5b7bdf6be98 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/configs/1n1d1e1w-s-n1.conf
/usr/bin/configs/1n1d1e1w-s-n2.conf
/usr/bin/configs/1n1d4e1w-s-n1.conf
/usr/bin/configs/1n1d4e1w-s-n2.conf
/usr/bin/configs/1n2d4e1w-s-n1.conf
/usr/bin/configs/1n2d4e1w-s-n2.conf
/usr/bin/configs/1n3d4e1w-s-n1.conf
/usr/bin/configs/1n3d4e1w-s-n2.conf
/usr/bin/configs/1n4d1e1w-s-n1.conf
/usr/bin/configs/1n4d1e1w-s-n2.conf
/usr/bin/configs/1n4d4e1w-s-n1.conf
/usr/bin/configs/1n4d4e1w-s-n2.conf
/usr/bin/configs/2n1d1e1w-s.conf
/usr/bin/configs/2n1d4e1w-s.conf
/usr/bin/configs/2n2d4e1w-s.conf
/usr/bin/configs/2n3d4e1w-s.conf
/usr/bin/configs/2n4d4e1w-s.conf
/usr/bin/scripts/accel_conf.py
/usr/bin/scripts/accel_conf.sh

%files dev
%defattr(-,root,root,-)
/usr/include/dml/detail/common/flags.hpp
/usr/include/dml/detail/common/specific_flags.hpp
/usr/include/dml/detail/common/status.hpp
/usr/include/dml/detail/common/types.hpp
/usr/include/dml/detail/common/utils/enum.hpp
/usr/include/dml/detail/ml/allocator.hpp
/usr/include/dml/detail/ml/buffer.hpp
/usr/include/dml/detail/ml/execution_path.hpp
/usr/include/dml/detail/ml/impl/core_interconnect.hpp
/usr/include/dml/detail/ml/impl/make_descriptor.hpp
/usr/include/dml/detail/ml/make_task.hpp
/usr/include/dml/detail/ml/options.hpp
/usr/include/dml/detail/ml/result.hpp
/usr/include/dml/detail/ml/task.hpp
/usr/include/dml/detail/ml/utils.hpp
/usr/include/dml/detail/ml/view.hpp
/usr/include/dml/dml.h
/usr/include/dml/dml.hpp
/usr/include/dml/dmldefs.h
/usr/include/dml/hl/data_view.hpp
/usr/include/dml/hl/detail/buffer.hpp
/usr/include/dml/hl/detail/execute.hpp
/usr/include/dml/hl/detail/handler.hpp
/usr/include/dml/hl/detail/make_result.hpp
/usr/include/dml/hl/detail/submit.hpp
/usr/include/dml/hl/detail/utils.hpp
/usr/include/dml/hl/execute.hpp
/usr/include/dml/hl/execution_interface.hpp
/usr/include/dml/hl/execution_path.hpp
/usr/include/dml/hl/handler.hpp
/usr/include/dml/hl/operations.hpp
/usr/include/dml/hl/result.hpp
/usr/include/dml/hl/sequence.hpp
/usr/include/dml/hl/status_code.hpp
/usr/include/dml/hl/submit.hpp
/usr/include/dml/hl/types.hpp
/usr/lib64/cmake/DML/DMLConfig.cmake
/usr/lib64/cmake/DML/DMLConfigVersion.cmake
/usr/lib64/cmake/DML/DMLTargets-relwithdebinfo.cmake
/usr/lib64/cmake/DML/DMLTargets.cmake

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/DML/d6b97f1ba83cfecb7d9dcb7165e8d5b7bdf6be98
